// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRcKFBcBUBzmZf4G3L2l3eSjxFZ6ED60',
    appId: '1:528084826045:web:5c5178c7137a579b7fc4d4',
    messagingSenderId: '528084826045',
    projectId: 'fadhlshop',
    authDomain: 'fadhlshop.firebaseapp.com',
    storageBucket: 'fadhlshop.firebasestorage.app',
    measurementId: 'G-64921NCSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeI_TS7SBgBOLbfCQHsaC0B-Ij55zrDFI',
    appId: '1:528084826045:android:fb7b3d5026cc76fd7fc4d4',
    messagingSenderId: '528084826045',
    projectId: 'fadhlshop',
    storageBucket: 'fadhlshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1QTgsZvNLRTOJ9vbJX_-Lj28gLC8za0',
    appId: '1:528084826045:ios:88f9842235e7cf897fc4d4',
    messagingSenderId: '528084826045',
    projectId: 'fadhlshop',
    storageBucket: 'fadhlshop.firebasestorage.app',
    iosBundleId: 'com.example.fadhl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK1QTgsZvNLRTOJ9vbJX_-Lj28gLC8za0',
    appId: '1:528084826045:ios:88f9842235e7cf897fc4d4',
    messagingSenderId: '528084826045',
    projectId: 'fadhlshop',
    storageBucket: 'fadhlshop.firebasestorage.app',
    iosBundleId: 'com.example.fadhl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpRcKFBcBUBzmZf4G3L2l3eSjxFZ6ED60',
    appId: '1:528084826045:web:dbb5b6b045b6206c7fc4d4',
    messagingSenderId: '528084826045',
    projectId: 'fadhlshop',
    authDomain: 'fadhlshop.firebaseapp.com',
    storageBucket: 'fadhlshop.firebasestorage.app',
    measurementId: 'G-QFKE5C0X5G',
  );
}
